[settings]
lockfile = true

[tools]
"go:github.com/maxbrunsfeld/counterfeiter/v6" = "latest"
"go:github.com/mikefarah/yq/v4" = "latest"
"go:github.com/sqlc-dev/sqlc/cmd/sqlc" = "latest"
"go:github.com/typelate/muxt/cmd/muxt" = "latest"

[env]
_.source = ".config/mise/env.sh"
